package configuration.util

object UserEvents {
  def CREATED="USER SUCCESSFULLY CREATED"
  def CREATIONFAILED ="USER CREATION FAILED"
  def DUPLICATEUSER ="DUPLICATE USER"
  def ACCOUNT_EXIST="ACCOUNT_EXIST"

}
