package domain.users

/**
  * Created by hashcode on 2017/02/23.
  */
object UserState {
  def CONFIRMED="CONFIRMED"
  def UNCONFIRMED="UNCONFIRMED"
  def SITEADMIN="SITEADMIN"
  def ADMIN="ADMIN"
  def MODERATOR="MODERATOR"
  def SUBSCRIBER="SUBSCRIBER"
  def EXPIRED="EXPIRED"
  def CURRENT="CURRENT"
  def VALIDATED="VALIDATED"
  def NOTVALIDATED="NOT VALIDATED"
}
